apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-data-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path" 