apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-deployment
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      containers:
      - name: adguardhome
        image: adguard/adguardhome
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 443
          protocol: UDP
        - containerPort: 3000
          protocol: TCP
        - containerPort: 853
          protocol: TCP
        - containerPort: 784
          protocol: UDP
        - containerPort: 8853
          protocol: UDP
        - containerPort: 5443
          protocol: TCP
        - containerPort: 5443
          protocol: UDP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: adguardhome-data
          mountPath: /opt/adguardhome/work
        - name: adguardhome-config
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: adguardhome-data
        persistentVolumeClaim:
          claimName: adguardhome-data-pvc
      - name: adguardhome-config
        persistentVolumeClaim:
          claimName: adguardhome-config-pvc